### ISSUE TITLE
unknown search element [gas-booster]

### ISSUE THREAD

**Issue by etienne-bondot** [graphaware/graph-aided-search#3]
EDIT: I just find the error after few hours of research, an old instance from an other version of elasticsearch was still running in background. I close this mistake. Thanks for your work here ;)

Hello,

I get this error using the node.js official plugin of elasticsearch with neo4j.

```
Elasticsearch TRACE: 2016-11-02T22:26:57Z
  -> POST http://localhost:9200/neo4j-index/School%2CEmployer%2CUserFacebook%2CUserEmail%2CPlace%2CCompanyDomain/_search
  {
    "query": {
      "query_string": {
        "fields": [
          "facebookName^10",
          "goodGmailName^7",
          "gmailEmail^10",
          "country^15",
          "city^15",
          "schoolName^30",
          "employerName^20",
          "placeName^15",
          "zip^5",
          "street^7",
          "domain^5"
        ],
        "query": "allan",
        "use_dis_max": true
      }
    },
    "gas-booster": {
      "name": "SearchResultCypherBooster",
      "query": "MATCH (n) WHERE n:UserEmail or n:UserFacebook WITH n AS n, (CASE WHEN exists(n.facebookEmail) or exists((n)-[:STUDIED_IN]->()) or exists(n.hometown) or size((n)-[]->())>30 THEN 1 else 0 end) as score RETURN n.uuid AS uuid, score",
      "identifier": "uuid",
      "scoreName": "score",
      "operator": "+"
    },
    "gas-filter": {
      "name": "SearchResultCypherFilter",
      "query": "MATCH (n:UserEmail) WITH n MATCH (n)<-[:HAS_ACCOUNT]-(father) WITH n, father WHERE exists((father)<-[:KNOWS]-()) RETURN n.uuid AS id UNION MATCH (n:UserFacebook) WITH n MATCH (n)<-[:HAS_ACCOUNT]-(father) WITH n, father WHERE exists((father)<-[:KNOWS]-()) RETURN n.uuid AS id"
    }
  }
  <- 400
  {
    "error": {
      "root_cause": [
        {
          "type": "search_parse_exception",
          "reason": "failed to parse search source. unknown search element [gas-booster]",
          "line": 1,
          "col": 243
        }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
        {
          "shard": 0,
          "index": "neo4j-index",
          "node": "TafSfQzVT1CTuW2gRv7Acw",
          "reason": {
            "type": "search_parse_exception",
            "reason": "failed to parse search source. unknown search element [gas-booster]",
            "line": 1,
            "col": 243
          }
        }
      ]
    },
    "status": 400
  }

Elasticsearch DEBUG: 2016-11-02T22:26:57Z
  Request complete

Trace: [search_parse_exception] failed to parse search source. unknown search element [gas-booster], with { line=1 col=243 }
    at /Users/bondot_e/Workspace/shortouch-api/app/controllers/users/users.controller.js:65:11
    at tryCallOne (/Users/bondot_e/Workspace/shortouch-api/node_modules/elasticsearch/node_modules/promise/lib/core.js:37:12)
    at /Users/bondot_e/Workspace/shortouch-api/node_modules/elasticsearch/node_modules/promise/lib/core.js:123:15
    at flush (/Users/bondot_e/Workspace/shortouch-api/node_modules/elasticsearch/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

What's giving me a headache is that I'm currently working locally. But if I request elasticsearch hosted on my distant server everything is working fine...

I used elasticsearch v2.3.2 :
`Version: 2.3.2, Build: b9e4a6a/2016-04-21T16:03:47Z, JVM: 1.8.0_60`

on my distant server :
`Version: 2.3.2, Build: b9e4a6a/2016-04-21T16:03:47Z, JVM: 1.8.0_91`

and I tried with graph-aid-search v2.3.2.0 (the version which is working fine on my distant server), v.2.3.2.2 (recommended on the README) and the last release v2.4.1.3 without any success.

elasticsearch logs: 
```
[2016-11-02 23:16:02,826][INFO ][node                     ] [Dirtnap] version[2.3.2], pid[30136], build[b9e4a6a/2016-04-21T16:03:47Z]
[2016-11-02 23:16:02,827][INFO ][node                     ] [Dirtnap] initializing ...
[2016-11-02 23:16:03,544][INFO ][plugins                  ] [Dirtnap] modules [reindex, lang-expression, lang-groovy], plugins [graph-aided-search], sites []
[2016-11-02 23:16:03,596][INFO ][env                      ] [Dirtnap] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [32gb], net total_space [232.6gb], spins? [unknown], types [hfs]
[2016-11-02 23:16:03,597][INFO ][env                      ] [Dirtnap] heap size [990.7mb], compressed ordinary object pointers [true]
[2016-11-02 23:16:03,598][WARN ][env                      ] [Dirtnap] max file descriptors [10240] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-11-02 23:16:06,129][INFO ][node                     ] [Dirtnap] initialized
[2016-11-02 23:16:06,130][INFO ][node                     ] [Dirtnap] starting ...
[2016-11-02 23:16:06,227][INFO ][transport                ] [Dirtnap] publish_address {127.0.0.1:9301}, bound_addresses {[fe80::1]:9301}, {[::1]:9301}, {127.0.0.1:9301}
[2016-11-02 23:16:06,231][INFO ][discovery                ] [Dirtnap] elasticsearch/F78p3vSDST-83RfYIVaG5Q
[2016-11-02 23:16:09,274][INFO ][cluster.service          ] [Dirtnap] new_master {Dirtnap}{F78p3vSDST-83RfYIVaG5Q}{127.0.0.1}{127.0.0.1:9301}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-11-02 23:16:09,315][INFO ][http                     ] [Dirtnap] publish_address {127.0.0.1:9201}, bound_addresses {[fe80::1]:9201}, {[::1]:9201}, {127.0.0.1:9201}
[2016-11-02 23:16:09,315][INFO ][node                     ] [Dirtnap] started
[2016-11-02 23:16:09,334][INFO ][gateway                  ] [Dirtnap] recovered [0] indices into cluster_state
```

So `graph-aided-search` is apparently successfully loaded.

I think I am following well my setup:

```
curl -XPOST 'localhost:9200/neo4j-index/_close'

curl -XPUT 'http://localhost:9200/neo4j-index/_settings?index.gas.neo4j.hostname=http://localhost:7474&index.gas.enable=true'
curl -XPUT 'http://localhost:9200/neo4j-index/_settings?index.gas.neo4j.user=neo4j&index.gas.neo4j.password=xxx'

curl -X PUT 'localhost:9200/neo4j-index/_settings' -d '{
"analysis": {
"filter": {
"autocomplete_filter": {
"type":     "edge_ngram",
"min_gram": 4,
"max_gram": 20
}
},
"analyzer": {
"autocomplete": {
"type":      "custom",
"tokenizer": "standard",
"filter": [
"lowercase",
"autocomplete_filter",
"asciifolding"
]
}
}
}
}'

curl -XPOST 'localhost:9200/neo4j-index/_open'
```

And then I performed my mapping.

Any suggestion ?

**Comment by linoan** [comment]
EDIT: I just saw you mentioned an existing running ES in background.
Unfortunately, I still can't figure out the problem

I am having the same problem.
Apparently you closed it, and seems like you solved it.
Mind to share what was wrong/missing?

**Comment by etienne-bondot** [comment]
As I said in my edit, I had my old version of elasticsearch still running in background even if I delete the sources.

You can check if this is your case with `ps aux | grep elasticsearch`

So I just manually killed the process with `sudo kill -9 <pid>` and then restart my new elasticsearch which contains the plugin.

And everything was working ! :)

**Comment by linoan** [comment]
I got the problem!
The docker running the install-plugin isn't working.
Haha, my bad thanks!

**Comment by TheBenzouine** [comment]
Hi, 
I am getting the same error message but for `gas-filter`. I am working on Windows so I found that the equivalent command to `ps aux | grep elasticsearch` is `TASKLIST /M elasticsearch` but that doesn't give me anything.  And when I only do `tasklist /v` or `tasklist /svc`I cannot find `elasticsearch` on the list of the processes even when running it.
Any thoughts?
Thanks!

**Comment by teeterc** [comment]
I'm also getting this error, but only when i use the java tcp client (port 9300).  http works fine (9200).  Any ideas?
